==Done== * Sometimes, we do not add Measures to columns or rows, but as a specific filter for one specific measure * In this case, projection-OP should be the filtered measure * However, we do not need an additional dice-OP for the measure, since it is already included in the projection-OP.
==Background info==
java.lang.UnsupportedOperationException: There should be an OLAP element
for each identifier, also this
one:[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX23lo_extendedprice]
	at
org.olap4j.driver.olap4ld.MdxMethodVisitor.visit(MdxMethodVisitor.java:849)
	at org.olap4j.mdx.IdentifierNode.accept(IdentifierNode.java:167) 	at
org.olap4j.driver.olap4ld.MdxMethodVisitor.callBraces(MdxMethodVisitor.java:680)
	at
org.olap4j.driver.olap4ld.MdxMethodVisitor.visit(MdxMethodVisitor.java:333)
	at org.olap4j.mdx.CallNode.accept(CallNode.java:156) 	at
org.olap4j.driver.olap4ld.MdxMethodVisitor.visit(MdxMethodVisitor.java:243)
	at org.olap4j.mdx.AxisNode.accept(AxisNode.java:76) 	at
org.olap4j.driver.olap4ld.MdxMethodVisitor.visit(MdxMethodVisitor.java:149)
	at org.olap4j.mdx.SelectNode.accept(SelectNode.java:102) 	at
org.olap4j.driver.olap4ld.Olap4ldCellSet.populate(Olap4ldCellSet.java:162)
	at
org.olap4j.driver.olap4ld.Olap4ldStatement.executeOlapQuery(Olap4ldStatement.java:357)
	at
org.olap4j.LD_Cubes_Explorer_QueryTest.executeStatement(LD_Cubes_Explorer_QueryTest.java:384)
	at
org.olap4j.LD_Cubes_Explorer_QueryTest.testSsb001MeasureDiceExampleOlap(LD_Cubes_Explorer_QueryTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616) 	at
junit.framework.TestCase.runTest(TestCase.java:154) 	at
junit.framework.TestCase.runBare(TestCase.java:127) 	at
junit.framework.TestResult$1.protect(TestResult.java:106) 	at
junit.framework.TestResult.runProtected(TestResult.java:124) 	at
junit.framework.TestResult.run(TestResult.java:109) 	at
junit.framework.TestCase.run(TestCase.java:118) 	at
junit.framework.TestSuite.runTest(TestSuite.java:208) 	at
junit.framework.TestSuite.run(TestSuite.java:203) 	at
org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)


[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX23lo_extendedprice]
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_extendedprice]

PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
PREFIX skosclass: <http://ddialliance.org/ontologies/skosclass#> 
PREFIX eus: <http://ontologycentral.com/2009/01/eurostat/ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX qb: <http://purl.org/linked-data/cube#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
select   ?httpolap4ldgooglecodecomgitOLAP4LD

INFO: Logical query plan to string: Rollup (Slice (Dice (Projection
(BaseCube
([httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23ds]),

 [httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_extendedprice]),

 ([httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_extendedprice])),

 [httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_custkey],
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_orderdate],
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_partkey],
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_suppkey],
Measures),

 [httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_partkey]
:
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_partkeyCodeList],
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_custkey]
:
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_custkeyCodeList])


SPARQL query: PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
PREFIX skosclass: <http://ddialliance.org/ontologies/skosclass#> 
PREFIX eus: <http://ontologycentral.com/2009/01/eurostat/ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX qb: <http://purl.org/linked-data/cube#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
select  
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllopartkey0
 ?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllocustkey0
 (SUM(?httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23loextendedprice)
as
?httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23loextendedprice)
 where {  ?obs
<http://olap4ld.googlecode.com/git/OLAP4LD-trunk/tests/ssb001/ttl/example.ttl#lo_partkey>
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllopartkey0.
?obs
<http://olap4ld.googlecode.com/git/OLAP4LD-trunk/tests/ssb001/ttl/example.ttl#lo_custkey>
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllocustkey0.
 FILTER ( ?Measures0 =
<http://olap4ld.googlecode.com/git/OLAP4LD-trunk/tests/ssb001/ttl/example.ttl#lo_extendedprice>
) ?obs
<http://olap4ld.googlecode.com/git/OLAP4LD-trunk/tests/ssb001/ttl/example.ttl#lo_extendedprice>
?httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23loextendedprice.}
group by 
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllopartkey0
 ?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllocustkey0
 order by 
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllopartkey0
 ?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllocustkey0


PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
PREFIX skosclass: <http://ddialliance.org/ontologies/skosclass#> 
PREFIX eus: <http://ontologycentral.com/2009/01/eurostat/ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX qb: <http://purl.org/linked-data/cube#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
select  
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllopartkey0
 ?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllocustkey0
 (SUM(?httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23loextendedprice)
as
?httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23loextendedprice)
 where {  ?obs
<http://olap4ld.googlecode.com/git/OLAP4LD-trunk/tests/ssb001/ttl/example.ttl#lo_partkey>
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllopartkey0.
?obs
<http://olap4ld.googlecode.com/git/OLAP4LD-trunk/tests/ssb001/ttl/example.ttl#lo_custkey>
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllocustkey0.
 FILTER () ?obs
<http://olap4ld.googlecode.com/git/OLAP4LD-trunk/tests/ssb001/ttl/example.ttl#lo_extendedprice>
?httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23loextendedprice.}
group by 
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllopartkey0
 ?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllocustkey0
 order by 
?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllopartkey0
 ?httpolap4ldgooglecodecomgitOLAP4LDtrunktestsssb001ttlexamplettllocustkey0


Problem:

* Sometimes, we do not add Measures to columns or rows, but as a
specific filter for one specific measure
* In this case, projection-OP should be the filtered measure
* However, we do not need an additional dice-OP for the measure, since
it is already included in the projection-OP.


SELECT
{[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_discount]}
ON COLUMNS
,{Members([httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_custkeyCodeList])}
ON ROWS FROM
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23ds]
WHERE {
[httpXXX3AXXX2FXXX2Folap4ldYYYgooglecodeYYYcomXXX2FgitXXX2FOLAP4LDZZZtrunkXXX2FtestsXXX2Fssb001XXX2FttlXXX2FexampleYYYttlXXX23lo_discount]
}